lsi:         false
name: Kingdom of Atlantia - Rapier Marshal
description: Rapier combat within the Kingdom of Atlantia
url: http://rapier.atlantia.sca.org
highlighter: true
encoding: "UTF-8"
markdown: kramdown
excerpt_separator: <!-- more -->
permalink:   pretty
paginate:    5
paginate_path: "/blog/page:num"
exclude:
  - README.txt
  - Rakefile
