lsi:         false
name: Kingdom of Atlantia - Rapier Marshal
description: Rapier combat within the Kingdom of Atlantia
url: http://rapier.atlantia.sca.org
highlighter: true
encoding: "UTF-8"
markdown: kramdown
excerpt_separator: <!-- more -->
permalink:   pretty
exclude:
  - README.txt
  - Rakefile
nav:
  - text: Index
    href: /
  - text: Rules
    href: /rules
  - text: Practices
    href: /practices
  - text: Marshals
    href: /marshals
  - text: Links
    href: /links
